server:
  port: 8080

spring:
  application:
    name: api-gateway

  r2dbc:
    url: r2dbc:postgresql://localhost:54033/gateway_db
    username: postgres
    password: Admin@123456

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: api-gateway