server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: api-gateway

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/postgres
    username: postgres
    password: Admin@123456

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/gateway-management

keycloak:
  server-url: http://localhost:8180
  realm: gateway-management
  client-id: api-gateway-management
  client-secret: lMokPC2fpSD7RUIHl6zNCNa12EHWDUIHZqvwN8itPOqzRT19N7GTmGlXWN3OfSFLLQ5AO3svznHykj9FDgdK0Z
  admin-client-id: gateway-admin-service
  admin-client-secret: L5uis6Mou3rVFURVFcCdhtAOPeKvJlUiB6WW7QEI9uGN1NMxUJC0QseihhW46ssctGXFlGy1BwENN8sxZ4gDU4

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - gateway
  endpoint:
    gateway:
      access: read-only
    health:
      show-details: always
  metrics:
    tags:
      application: api-gateway
