server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: api-gateway

  r2dbc:
    url: r2dbc:postgresql://localhost:54033/gateway_db
    username: postgres
    password: Admin@123456

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/gateway-management

keycloak:
  server-url: http://localhost:8180
  realm: gateway-management
  client-id: api-gateway-management
  client-secret: WTRRCNQ4Uwsk37OHO3WunZk7eO2yq2Vpnw90UbRVNVtyPMdwBu6ic2ON0RmYFBKi6aBtQmJV2nSTGoQcPblYdV
  admin-client-id: gateway-admin-service
  admin-client-secret: tMocpXqApK4FtJZyNaQdBUc2WmFBy32kLUC7LSu8DbvRdzyoWkXwAMd73eXA87vMRSTYYTkQv8zORcYcU7g82b

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - gateway
  endpoint:
    gateway:
      access: read-only
    health:
      show-details: always
  metrics:
    tags:
      application: api-gateway
